### ISSUE TITLE
Undefined VTune installation directory

### ISSUE THREAD

**Issue by ziyaointl** [oleksandr-pavlyk/itt-python#6]
I am using a new python2 environment created by python3/3.6-anaconda-4.4. A screenshot of the error can be found below
<img width="1552" alt="Screen Shot 2019-05-05 at 1 22 41 AM" src="https://user-images.githubusercontent.com/18119047/57190899-ab71e100-6ed4-11e9-9592-36188cea88bb.png">

**Comment by rcthomas** [comment]
Please try the install-skip-build branch.

**Comment by ziyaointl** [comment]
Thanks! The installation worked. I am still having some trouble getting user task labels to display though. Maybe I'll open another issue if I couldn't get it to work.
